name: Build and Deploy to Staging

on:
  pull_request:
    branches: [ master ]

env:
  WEBAPP_NAME: sample-webapp 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Package webapp
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.WEBAPP_NAME }}
        path: ./publish
  
  staging_deploy:

    runs-on: ubuntu-latest

    needs: [build]
    env:
      APP_SERVICE_NAME: tiberna-actions
      APP_SERVICE_SLOT: staging
    steps:
      - name: Download webapp
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.WEBAPP_NAME }}
          path: ${{ env.WEBAPP_NAME }}

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.APP_SERVICE_NAME }}
          slot-name: ${{ env.APP_SERVICE_SLOT }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROFILE_STAGING }}
          package: ${{ env.WEBAPP_NAME }}
